#!/usr/bin/env bash
# Copyright 2026 Jaziel Guerrero
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Starts the single-node WorkDock deployment in a single run.
#
# The stack uses the file-backed secrets provider, so there is no external
# secrets service to configure between runs. Machine-managed values
# (database password, SigNoz secret) are generated once into
# docker/generated.env. User-provided values live directly in config.yaml
# and github-app.pem.

set -Eeuo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root_dir"

require_command() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  }
}

require_command docker
require_command openssl

# *-------------------------------------------------------------------------*
# * Machine-managed secrets                                                 *
# *-------------------------------------------------------------------------*

generated_env="docker/generated.env"

if [[ ! -f "$generated_env" ]]; then
  mkdir -p docker
  {
    printf '# Generated by scripts/docker-up.sh. Do not commit or edit by hand.\n'
    printf 'POSTGRES_PASSWORD=%s\n' "$(openssl rand -hex 16)"
    printf 'SIGNOZ_JWT_SECRET=%s\n' "$(openssl rand -hex 32)"
  } > "$generated_env"
  chmod 600 "$generated_env"
  printf 'Generated %s\n' "$generated_env"
fi

# shellcheck disable=SC1091
set -a
source "$generated_env"
set +a

compose_args=(compose --env-file "$generated_env")

# *-------------------------------------------------------------------------*
# * User configuration checks                                               *
# *-------------------------------------------------------------------------*

if [[ ! -f config.yaml ]]; then
  cp config.example.yaml config.yaml
  printf 'Created config.yaml from config.example.yaml\n'
fi

placeholders="$(grep -o 'replace-with-[a-z0-9-]*' config.yaml || true)"

needs_pem=0
if [[ ! -f github-app.pem ]]; then
  needs_pem=1
  printf 'WARNING: github-app.pem not found. GitHub App integration will fail until the private key is placed at the repository root.\n' >&2
fi

# *-------------------------------------------------------------------------*
# * Render Tern migration config                                            *
# *-------------------------------------------------------------------------*

mkdir -p docker/workdock

cat > docker/workdock/tern.conf <<EOF
[database]
host = postgres
port = 5432
database = workdock
user = workdock
password = $POSTGRES_PASSWORD
sslmode = disable
version_table = public.schema_version
EOF

chmod 644 docker/workdock/tern.conf

# *-------------------------------------------------------------------------*
# * Start the stack                                                         *
# *-------------------------------------------------------------------------*

if ! docker "${compose_args[@]}" up --build -d --wait; then
  printf 'Timed out waiting for the stack to become healthy. Inspect: docker compose logs\n' >&2
  exit 1
fi

# *-------------------------------------------------------------------------*
# * Config change watcher                                                   *
# *-------------------------------------------------------------------------*

# Recreate the engine container whenever config.yaml changes so edits apply
# without manual restarts. Uses docker compose watch (Compose v2.22+).

watch_pid_file="docker/.watch.pid"

if [[ -f "$watch_pid_file" ]] && kill -0 "$(cat "$watch_pid_file")" 2>/dev/null; then
  printf 'Config watcher already running (pid %s).\n' "$(cat "$watch_pid_file")"
else
  nohup docker "${compose_args[@]}" watch workdock > docker/.watch.log 2>&1 &
  echo $! > "$watch_pid_file"
  printf 'Watching config.yaml for changes (pid %s). Stop with: kill %s\n' "$(cat "$watch_pid_file")" "$(cat "$watch_pid_file")"
fi

printf '\nWorkDock is running at http://localhost:8080\n'
printf 'SigNoz is running at http://localhost:8082\n'

printf '\nDatabase URL for config.yaml (postgres.database_url):\n'
printf '  postgresql://workdock:%s@postgres:5432/workdock\n' "$POSTGRES_PASSWORD"
printf 'The password comes from %s and matches the value already used by migrations.\n' "$generated_env"

if [[ -n "$placeholders" || "$needs_pem" -eq 1 ]]; then
  printf '\nTo complete the configuration:\n'
  printf '  1. Edit config.yaml at the repository root and replace every replace-with-* placeholder\n'
  printf '     with your Linear, GitHub App, Daytona, and OpenCode values:\n'
  if [[ -n "$placeholders" ]]; then
    printf '       %s\n' "$placeholders"
  fi
  printf '  2. Place the GitHub App private key at github-app.pem in the repository root.\n'
  printf '     Point github.private_key_path at /app/config/github-app.pem.\n'
  printf '  3. Set postgres.database_url to the URL printed above. Do not use 127.0.0.1 from inside the container.\n'
  printf '  4. Save config.yaml. The engine container restarts automatically on save (config watcher),\n'
  printf '     or rerun this script if the watcher is not available.\n'
  printf '  5. Check engine health: docker compose logs -f workdock\n'
else
  printf '\nAll configuration values are set. WorkDock is ready to use.\n'
fi