package metrics

import (
	"fmt"

	"go.opentelemetry.io/otel/metric"
)

type HarnessMetrics struct {
	SessionCount               metric.Int64Counter
	TokenUsage                 metric.Int64Counter
	CostUsage                  metric.Float64Counter
	ToolDuration               metric.Float64Histogram
	ToolCount                  metric.Int64Counter
	CacheCount                 metric.Int64Counter
	SessionDuration            metric.Float64Histogram
	MessageCount               metric.Int64Counter
	SessionTokenTotal          metric.Int64Histogram
	SessionCostTotal           metric.Float64Histogram
	ModelUsage                 metric.Int64Counter
	RetryCount                 metric.Int64Counter
	SessionInputTokens         int64
	SessionOutputTokens        int64
	SessionReasoningTokens     int64
	SessionCacheReadTokens     int64
	SessionCacheCreationTokens int64
	SessionCost                float64
	ToolStarts                 map[string]int64
}

func NewHarnessMetrics(harness string, meter metric.Meter) (*HarnessMetrics, error) {
	sessionCount, err := meter.Int64Counter(
		fmt.Sprintf("%s.session.count", harness),
		metric.WithUnit("{session}"),
		metric.WithDescription(fmt.Sprintf("Number of %s sessions created", harness)),
	)

	if err != nil {
		return nil, err
	}

	tokenUsage, err := meter.Int64Counter(
		fmt.Sprintf("%s.token.usage", harness),
		metric.WithUnit("{token}"),
		metric.WithDescription(fmt.Sprintf("Tokens consumed by %s", harness)),
	)

	if err != nil {
		return nil, err
	}

	costUsage, err := meter.Float64Counter(
		fmt.Sprintf("%s.cost.usage", harness),
		metric.WithUnit("USD"),
		metric.WithDescription(fmt.Sprintf("LLM cost incurred by %s", harness)),
	)

	if err != nil {
		return nil, err
	}

	toolDuration, err := meter.Float64Histogram(
		fmt.Sprintf("%s.tool.duration", harness),
		metric.WithUnit("ms"),
		metric.WithDescription("Tool execution duration"),
	)

	if err != nil {
		return nil, err
	}

	toolCount, err := meter.Int64Counter(
		fmt.Sprintf("%s.tool.count", harness),
		metric.WithUnit("{call}"),
		metric.WithDescription("Tool calls executed"),
	)

	if err != nil {
		return nil, err
	}

	sessionDuration, err := meter.Float64Histogram(
		fmt.Sprintf("%s.session.duration", harness),
		metric.WithUnit("ms"),
		metric.WithDescription(fmt.Sprintf("%s session duration", harness)),
	)

	if err != nil {
		return nil, err
	}

	messageCount, err := meter.Int64Counter(
		fmt.Sprintf("%s.message.count", harness),
		metric.WithUnit("{message}"),
		metric.WithDescription("Completed assistant messages"),
	)

	if err != nil {
		return nil, err
	}

	sessionTokenTotal, err := meter.Int64Histogram(
		fmt.Sprintf("%s.session.token.total", harness),
		metric.WithUnit("{token}"),
		metric.WithDescription("Total tokens consumed by a session"),
	)

	if err != nil {
		return nil, err
	}

	sessionCostTotal, err := meter.Float64Histogram(
		fmt.Sprintf("%s.session.cost.total", harness),
		metric.WithUnit("USD"),
		metric.WithDescription("Total cost of a session"),
	)

	if err != nil {
		return nil, err
	}

	modelUsage, err := meter.Int64Counter(
		fmt.Sprintf("%s.model.usage", harness),
		metric.WithUnit("{message}"),
		metric.WithDescription("Messages generated by model"),
	)

	if err != nil {
		return nil, err
	}

	retryCount, err := meter.Int64Counter(
		fmt.Sprintf("%s.retry.count", harness),
		metric.WithUnit("{retry}"),
		metric.WithDescription("API retries"),
	)

	if err != nil {
		return nil, err
	}

	cacheCount, err := meter.Int64Counter(
		fmt.Sprintf("%s.cache.count", harness),
		metric.WithUnit("{operation}"),
		metric.WithDescription("Cache operations"),
	)

	if err != nil {
		return nil, err
	}

	return &HarnessMetrics{
		SessionCount:      sessionCount,
		TokenUsage:        tokenUsage,
		CostUsage:         costUsage,
		ToolDuration:      toolDuration,
		ToolCount:         toolCount,
		CacheCount:        cacheCount,
		SessionDuration:   sessionDuration,
		MessageCount:      messageCount,
		SessionTokenTotal: sessionTokenTotal,
		SessionCostTotal:  sessionCostTotal,
		ModelUsage:        modelUsage,
		RetryCount:        retryCount,
	}, nil
}
